C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Training Accuracy: 0.938249736541178
Testing Accuracy: 0.9370165250341936
Confusion Matrix : 
 [[20686     1     0     0     0     8     0     1     0     0     0]
 [   11 16964     0     0     0     0     0     3     0     0     0]
 [    0     0    24     0     0     0     0   402     0     0     6]
 [   25    46     0     0     0     0     0     0     0     0     0]
 [   17   613     0     0     0     0     0     0     0     0     0]
 [   18    83     0     0     0     0     0     3     0     0     0]
 [  149   719     0     0    43     0    51    37     0     0     0]
 [    0     0   269     0     0     0     2  4051     0     0     7]
 [    5     2     0     0     0     0     0     0     0     0     0]
 [    0     9     1     0     0     0    22    41     0     0     0]
 [    0     0     5     0     0     0     0   261     0     0    14]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

       clear       0.99      1.00      0.99     20696
      clouds       0.92      1.00      0.96     16978
     drizzle       0.08      0.06      0.07       432
        dust       0.00      0.00      0.00        71
         fog       0.00      0.00      0.00       630
        haze       0.00      0.00      0.00       104
        mist       0.68      0.05      0.09       999
        rain       0.84      0.94      0.89      4329
       smoke       0.00      0.00      0.00         7
        snow       0.00      0.00      0.00        73
thunderstorm       0.52      0.05      0.09       280

    accuracy                           0.94     44599
   macro avg       0.37      0.28      0.28     44599
weighted avg       0.91      0.94      0.92     44599



In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score


In [10]:

dataset = pd.read_csv('weather_features.csv')
dataset = dataset.dropna()

dataset['weather_main'].unique()

dataset['city_name'].unique()

le = LabelEncoder()
dataset["dt_iso"] = le.fit_transform(dataset["dt_iso"])
dataset["city_name"] = le.fit_transform(dataset["city_name"])
dataset["weather_description"] = le.fit_transform(dataset["weather_description"])
dataset["weather_icon"] = le.fit_transform(dataset["weather_icon"])
dataset


dt_iso  city_name     temp  temp_min  temp_max  pressure  humidity  \
0            0          4  270.475   270.475   270.475      1001        77   
1            1          4  270.475   270.475   270.475      1001        77   
2            2          4  269.686   269.686   269.686      1002        78   
3            3          4  269.686   269.686   269.686      1002        78   
4            4          4  269.686   269.686   269.686      1002        78   
...        ...        ...      ...       ...       ...       ...       ...   
178391   35059          3  287.760   287.150   288.150      1028        54   
178392   35060          3  285.760   285.150   286.150      1029        62   
178393   35061          3  285.150   285.150   285.150      1028        58   
178394   35062          3  284.150   284.150   284.150      1029        57   
178395   35063          3  283.970   282.150   285.150      1029        70   

        wind_speed  wind_deg  rain_1h  rain_3h  snow_3h  clouds_all  \
0                1        62      0.0      0.0      0.0           0   
1                1        62      0.0      0.0      0.0           0   
2                0        23      0.0      0.0      0.0           0   
3                0        23      0.0      0.0      0.0           0   
4                0        23      0.0      0.0      0.0           0   
...            ...       ...      ...      ...      ...         ...   
178391           3        30      0.0      0.0      0.0           0   
178392           3        30      0.0      0.0      0.0           0   
178393           4        50      0.0      0.0      0.0           0   
178394           4        60      0.0      0.0      0.0           0   
178395           3        50      0.0      0.0      0.0           0   

        weather_id weather_main  weather_description  weather_icon  
0              800        clear                   33             2  
1              800        clear                   33             2  
2              800        clear                   33             2  
3              800        clear                   33             2  
4              800        clear                   33             2  
...            ...          ...                  ...           ...  
178391         800        clear                   33             2  
178392         800        clear                   33             2  
178393         800        clear                   33             2  
178394         800        clear                   33             2  
178395         800        clear                   33             2  

[178396 rows x 17 columns]

In [11]:
x = dataset.drop(['weather_main'], axis=1)
y = dataset['weather_main']

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.25, random_state = 0)


In [12]:
classifier = LogisticRegression(solver='lbfgs', max_iter=400)
classifier.fit(xtrain, ytrain)

y_pred = classifier.predict(xtest)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [17]:
print ("Training Accuracy: {}".format(classifier.score(xtrain, ytrain)))
predicted = classifier.predict(xtest)

print ("Testing Accuracy: {}".format(classifier.score(xtest,ytest)))
cv_accuracy = cross_val_score(estimator=classifier, X=xtrain, y=ytrain, cv=10)
print("Accuracy using 10 folds: ")
print(cv_accuracy)

cm = confusion_matrix(ytest, y_pred)
print ("Confusion Matrix : \n", cm)
print (classification_report(ytest, y_pred))

Training Accuracy: 0.938249736541178
Testing Accuracy: 0.9370165250341936


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the dat

Accuracy using 10 folds: 
[0.94133034 0.93946188 0.93983558 0.93654709 0.94200299 0.93849028
 0.93692078 0.93841094 0.94311981 0.943942  ]
Confusion Matrix : 
 [[20686     1     0     0     0     8     0     1     0     0     0]
 [   11 16964     0     0     0     0     0     3     0     0     0]
 [    0     0    24     0     0     0     0   402     0     0     6]
 [   25    46     0     0     0     0     0     0     0     0     0]
 [   17   613     0     0     0     0     0     0     0     0     0]
 [   18    83     0     0     0     0     0     3     0     0     0]
 [  149   719     0     0    43     0    51    37     0     0     0]
 [    0     0   269     0     0     0     2  4051     0     0     7]
 [    5     2     0     0     0     0     0     0     0     0     0]
 [    0     9     1     0     0     0    22    41     0     0     0]
 [    0     0     5     0     0     0     0   261     0     0    14]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

       clear       0.99      1.00      0.99     20696
      clouds       0.92      1.00      0.96     16978
     drizzle       0.08      0.06      0.07       432
        dust       0.00      0.00      0.00        71
         fog       0.00      0.00      0.00       630
        haze       0.00      0.00      0.00       104
        mist       0.68      0.05      0.09       999
        rain       0.84      0.94      0.89      4329
       smoke       0.00      0.00      0.00         7
        snow       0.00      0.00      0.00        73
thunderstorm       0.52      0.05      0.09       280

    accuracy                           0.94     44599
   macro avg       0.37      0.28      0.28     44599
weighted avg       0.91      0.94      0.92     44599

